//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APTEST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_DonVi
    {
        public string MaDonVi { get; set; }
        public string TenDonVi { get; set; }
        public string DiaChi { get; set; }
        public string SoDienThoai { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
        public string DonViCapTren { get; set; }
        public Nullable<int> MaTinh { get; set; }
        public Nullable<int> MaHuyen { get; set; }
        public Nullable<int> Cap { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public string IDCapTren { get; set; }
        public string NganHang { get; set; }
        public string MaQHNS { get; set; }
        public string LapBang { get; set; }
        public string KeToanTruong { get; set; }
        public string HieuTruong { get; set; }
    }
}
