//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APTEST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VB_TT_File
    {
        public string MaDonVi { get; set; }
        public string ID { get; set; }
        public string DuongDan { get; set; }
        public string TenFile { get; set; }
        public string IDVB { get; set; }
        public string Extension { get; set; }
        public string MineType { get; set; }
        public string Loai { get; set; }
    }
}
